// Code generated by MockGen. DO NOT EDIT.
// Source: go-bank/worker (interfaces: TaskDistributor)

// Package mockwrk is a generated GoMock package.
package mockwrk

import (
	context "context"
	worker "go-bank/internal/worker"
	reflect "reflect"

	asynq "github.com/hibiken/asynq"
	gomock "go.uber.org/mock/gomock"
)

// MockTaskDistributor is a mock of TaskDistributor interface.
type MockTaskDistributor struct {
	ctrl     *gomock.Controller
	recorder *MockTaskDistributorMockRecorder
}

// MockTaskDistributorMockRecorder is the mock recorder for MockTaskDistributor.
type MockTaskDistributorMockRecorder struct {
	mock *MockTaskDistributor
}

// NewMockTaskDistributor creates a new mock instance.
func NewMockTaskDistributor(ctrl *gomock.Controller) *MockTaskDistributor {
	mock := &MockTaskDistributor{ctrl: ctrl}
	mock.recorder = &MockTaskDistributorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskDistributor) EXPECT() *MockTaskDistributorMockRecorder {
	return m.recorder
}

// SendVerifyEmailTask mocks base method.
func (m *MockTaskDistributor) SendVerifyEmailTask(arg0 context.Context, arg1 *worker.VerifyEmailPayload, arg2 ...asynq.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendVerifyEmailTask", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendVerifyEmailTask indicates an expected call of SendVerifyEmailTask.
func (mr *MockTaskDistributorMockRecorder) SendVerifyEmailTask(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendVerifyEmailTask", reflect.TypeOf((*MockTaskDistributor)(nil).SendVerifyEmailTask), varargs...)
}
